# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Command L10n Update
on:
  issue_comment:
    types: [created]

jobs:
  init:
    runs-on: ubuntu-latest

    # On pull requests and if the comment starts with `/l10n-update`
    if: github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/l10n-update')

    outputs:
      arg1: ${{ steps.command.outputs.arg1 }}
      head_ref: ${{ steps.comment-branch.outputs.head_ref }}

    steps:
      - name: Add reaction on start
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          repository: ${{ github.event.repository.full_name }}
          comment-id: ${{ github.event.comment.id }}
          reaction-type: "+1"

      - name: Parse command
        uses: skjnldsv/parse-command-comment@master
        id: command

      - name: Init branch
        uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

  process:
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout ${{ needs.init.outputs.head_ref }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          fetch-depth: 0
          ref: ${{ needs.init.outputs.head_ref }}

      - name: Setup git
        run: |
          git config --local user.email "nextcloud-command@users.noreply.github.com"
          git config --local user.name "nextcloud-command"

      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v3
        with:
          node-version-file: package.json

      - name: Install dependencies & build l10n
        run: |
          npm ci
          npm run l10n:extract --if-present

      - name: Commit and push default
        if: ${{ needs.init.outputs.arg1 != 'fixup' && needs.init.outputs.arg1 != 'amend' }}
        run: |
          git add .
          git commit --signoff -m 'Updating l10n asset'
          git push origin ${{ needs.init.outputs.head_ref }}

      - name: Commit and push fixup
        if: ${{ needs.init.outputs.arg1 == 'fixup' }}
        run: |
          git add .
          git commit --fixup=HEAD --signoff
          git push origin ${{ needs.init.outputs.head_ref }}

      - name: Commit and push amend
        if: ${{ needs.init.outputs.arg1 == 'amend' }}
        run: |
          git add .
          git commit --amend --no-edit --signoff
          git push --force origin ${{ needs.init.outputs.head_ref }}

      - name: Add reaction on failure
        uses: peter-evans/create-or-update-comment@v4
        if: failure()
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          repository: ${{ github.event.repository.full_name }}
          comment-id: ${{ github.event.comment.id }}
          reaction-type: "-1"
