# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: L10n
on: pull_request

jobs:
  l10n-extract-check:
    runs-on: ubuntu-latest

    name: Pot check
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v3
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm ci

      - name: Extract l10n files
        run: npm run l10n:extract

      - name: Check l10n file changes
        run: bash -c "[[ ! \"`git status --porcelain l10n`\" ]] || ( echo 'Uncommited l10n changes. Run \`npm run l10n:extract\`.' && exit 1 )"
