# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Update server styling

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: read

jobs:
  server-styling-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Download css
        run: |
          cd styleguide/assets
          # Fix img css import
          curl https://nextcloud.github.io/server/apps/theming/css/default.css | sed 's|/apps/theming/img|./img|g' > default.css
          # Fix icons and img css import
          curl https://nextcloud.github.io/server/core/css/server.css | sed 's|../../dist/icons.css|./icons.css|g' | sed 's|../img|./img|g' > server.css
          curl https://nextcloud.github.io/server/dist/icons.css --output icons.css

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: "chore(assets): Update styling from server"
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: automated/noid/server-styling-update
          title: Automated styling update from server
          add-paths: styleguide/assets
          body: |
            Auto-generated update of our locally cached css styling from
             * https://nextcloud.github.io/server/apps/theming/css/default.css
             * https://nextcloud.github.io/server/core/css/server.css
             * https://nextcloud.github.io/server/dist/icons.css
          labels: |
            dependencies
            3. to review
